### ISSUE TITLE
Quorum flexibility

### ISSUE THREAD

**Issue by NickGlaettli** [polettif/proporz#3]
While working with your library, I found an issue calculating seat allocation for Zurich's cantonal elections. The canton of Zurich sets the quorum at _either_ 0.05 in at least 1 district _or_ 0.03 overall. The `pukelsheim` function, however, does not allow for that.  It would be great if you could add this option to the function.

Thank you for the amazing work!

**Comment by polettif** [comment]
I don't remember the implementation in detail but according to the documentation for [biprop_quorum](https://polettif.github.io/proporz/reference/biprop_quorum.html) it _should_ work in the way you describe it. I'll have a look, I probably mixed up something there. 

Thanks, I'm glad the package is useful!

**Comment by polettif** [comment]
The documentation is indeed not correct there, it's necessary to pass both quorums (not either/or), as you said. I'll rework the quorum calculations and add an option of some sort, thanks for pointing this out.

**Comment by polettif** [comment]
This turned out to be a bit tricky, let me know if you run into issues with the new approach.

**Comment by NickGlaettli** [comment]
thx
